export { default as H1 } from './Heading/H1.vue'
export { default as H2 } from './Heading/H2.vue'
export { default as H3 } from './Heading/H3.vue'
export { default as H4 } from './Heading/H4.vue'
export { default as H5 } from './Heading/H5.vue'
export { default as H6 } from './Heading/H6.vue'

export { default as Display1 } from './Display/Display1.vue'
export { default as Display2 } from './Display/Display2.vue'
export { default as Display3 } from './Display/Display3.vue'
export { default as Display4 } from './Display/Display4.vue'
export { default as Display5 } from './Display/Display5.vue'
export { default as Display6 } from './Display/Display6.vue'

export { default as Paragraph } from './Paragraph/paragraph.vue'
