export { default as AddedPeople } from '@/components/addEmployee/addEmployeeModals/ModalItems/AddedPeople.vue'
export { default as CSVSheet } from '@/components/addEmployee/addEmployeeModals/ModalItems/CSVSheet.vue'
export { default as SearchPeople } from '@/components/addEmployee/addEmployeeModals/ModalItems/SearchPeople.vue'
export { default as SearchResult } from '@/components/addEmployee/addEmployeeModals/ModalItems/SearchResult.vue'
export { default as SharingLink } from '@/components/addEmployee/addEmployeeModals/ModalItems/SharingLink.vue'
